apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    monitoring: "true"   # <-- label pour ServiceMonitor
spec:
  selector:
    app: api             # <-- doit matcher le label des pods
  ports:
    - name: http
      port: 3000
      targetPort: 3000
