frontend:
  repository: aabda2006/3tiers-frontend
  tag: "13e1794ba5c5155c241fb441222f108bfaa0e6c8"
  replicas: 3
  apiUrl: "http://api:3000"
  nodePort: 30080

api:
  repository: aabda2006/3tiers-api
  tag: "13e1794ba5c5155c241fb441222f108bfaa0e6c8"
  replicas: 2

postgres:
  image: postgres:15
  storage: 5Gi
  existingClaim: ""
