frontend:
  repository: aabda2006/3tiers-frontend
  tag: "1a5bab1f32bad15a0cdd597fa46d1898a4db7447"
  replicas: 3
  apiUrl: "http://api:3000"
  nodePort: 30080

api:
  repository: aabda2006/3tiers-api
  tag: "1a5bab1f32bad15a0cdd597fa46d1898a4db7447"
  replicas: 2

postgres:
  image: postgres:15
  storage: 5Gi
  existingClaim: ""
