frontend:
  repository: aabda2006/3tiers-frontend
  tag: "a976305cce37c735d6f7bd97f3c04069a92ecbcc"
  replicas: 3
  apiUrl: "http://api:3000"
  nodePort: 30080

api:
  repository: aabda2006/3tiers-api
  tag: "a976305cce37c735d6f7bd97f3c04069a92ecbcc"
  replicas: 2

postgres:
  image: postgres:15
  storage: 5Gi
  existingClaim: ""
