frontend:
  image: aabda2006/3tiers-frontend:latest
  replicas: 3
  apiUrl: "http://api:3000"
  nodePort: 30080

api:
  image: aabda2006/3tiers-api:latest
  replicas: 2

postgres:
  image: postgres:15
  storage: 5Gi
  existingClaim: ""
