frontend:
  repository: aabda2006/3tiers-frontend
  tag: "43147d10c91560986223b3e3cc45cdf2687ec746"
  replicas: 3
  apiUrl: "http://api:3000"
  nodePort: 30080

api:
  repository: aabda2006/3tiers-api
  tag: "43147d10c91560986223b3e3cc45cdf2687ec746"
  replicas: 2

postgres:
  image: postgres:15
  storage: 5Gi
  existingClaim: ""
