frontend:
  repository: aabda2006/3tiers-frontend
  tag: "9443f88ce8a081537cee6d024ce5222f734a8268"
  replicas: 3
  apiUrl: "http://api:3000"
  nodePort: 30080

api:
  repository: aabda2006/3tiers-api
  tag: "9443f88ce8a081537cee6d024ce5222f734a8268"
  replicas: 2

postgres:
  image: postgres:15
  storage: 5Gi
  existingClaim: ""
