frontend:
  repository: aabda2006/3tiers-frontend
  tag: "506b7da464415e5152837394f152ce5b792b4620"
  replicas: 3
  apiUrl: "http://api:3000"
  nodePort: 30080

api:
  repository: aabda2006/3tiers-api
  tag: "506b7da464415e5152837394f152ce5b792b4620"
  replicas: 2

postgres:
  image: postgres:15
  storage: 5Gi
  existingClaim: ""
