apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: monitoring
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      monitoring: "true"   # <-- match le label du service
  namespaceSelector:
    matchNames:
      - my-app
  endpoints:
    - port: http            # <-- doit correspondre au port nommÃ© du service
      path: /metrics
      interval: 15s
